/* App shell: navigation, footer, PWA install, landing page content */
const NAV=[['index.html','home','Home'],['generator.html','generator','Paper Generator'],['templates.html','templates','Templates'],['about.html','about','About'],['contact.html','contact','Contact']];
$('#nav').innerHTML=`<nav class="glass"><a href="index.html" class="logo"><img src="assets/images/logo-mark.png" alt="" width="34" height="34"><span class="wm">Ask<em>Paper</em>Gen</span></a><button class="btn" id="burger" aria-label="Menu">☰</button><div class="links">${NAV.map(n=>`<a class="l ${n[1]===PAGE?'on':''}" href="${n[0]}">${n[2]}</a>`).join('')}<button class="btn" data-install style="display:none">⬇ Install</button><a class="btn p" href="generator.html?new=1">Create Paper</a></div></nav>`;
$('#foot').innerHTML=`<div class="fgrid"><div class="fb"><a class="logo" href="index.html"><img src="assets/images/logo-mark.png" width="34" height="34" alt=""><span class="wm">Ask<em>Paper</em>Gen</span></a><p>Create. Format. Print.<br>Professional exam papers, right in your browser. Your papers stay on your device.</p></div><div><div class="fh">// product</div><a href="generator.html">Paper Generator</a><a href="templates.html">Templates</a><a href="generator.html?scan=1">Scan to Paper</a><button class="flink" data-install>Install app</button></div><div><div class="fh">// company</div><a href="about.html">About</a><a href="contact.html">Contact</a><a href="https://ahsanamingorsi.com" target="_blank" rel="noopener">Developer portfolio</a></div><div><div class="fh">// connect</div><a href="https://github.com/ahsanamingorsi" target="_blank" rel="noopener">GitHub</a><a href="https://www.linkedin.com/in/ahsanamingorsi" target="_blank" rel="noopener">LinkedIn</a><a href="https://www.instagram.com/ahsanamingorsi" target="_blank" rel="noopener">Instagram</a><a href="https://wa.me/923495473628" target="_blank" rel="noopener">WhatsApp</a></div></div><div class="fbot"><span>© 2026 AskPaperGen. All rights reserved.</span><span>Designed and developed by <a href="https://ahsanamingorsi.com" target="_blank" rel="noopener">Ahsan Amin Gorsi</a></span></div>`;
$('#burger').onclick=()=>$('nav .links').classList.toggle('open');
/* ---- landing ---- */
if(PAGE==='home'){
 const FE=['MCQs','Short Questions','Long Questions','Tables','Images','Urdu RTL Support','Custom Headers','Scan to Paper','Print Ready','PDF Export'],FD=['Unlimited options','Quick marks','With answer lines','Editable grids','From your device','Right-to-left layout','Logo & 7 header designs','Photo to question','A4 print CSS','Via browser dialog'];
 const GL=['☑','✎','¶','▦','▣','ع','◧','⌖','⎙','⇩'];
$('#feats').innerHTML=FE.map((f,i)=>`<div class="glass feat"><span class="n">${String(i+1).padStart(2,'0')}</span><div class="ico">${GL[i]}</div><b>${f}</b><span>${FD[i]}</span></div>`).join('');
 $('#how').innerHTML=[['Choose','Pick one of eight templates or start from a blank paper.'],['Add','Type questions, or scan them from a photo.'],['Preview','Watch the A4 paper update live, with header designs and Urdu RTL.'],['Print','Print or save as PDF. Works offline once installed.']].map((h,i)=>`<div class="glass step"><span class="num">0${i+1}</span><h3>${h[0]}</h3><p>${h[1]}</p></div>`).join('');
 
 const HD={classic:'Centered title with a clean rule',banner:'Solid colour band, white text',gradient:'Blue-to-cyan gradient band',split:'Institution left, exam title pill right',ribbon:'Centered title with ribbon label',modern:'Left accent edge, modern look',seal:'Formal ornament between rules'};
$('#hgal').innerHTML=HS.map(([v,n])=>`<div class="glass tc" style="cursor:pointer" data-h="${v}"><div class="th">${render({meta:{...DM,inst:'Horizon Academy',exam:'Annual Examination',subject:'Science',cls:'Grade 9',marks:'50',time:'2 Hours'},style:{...DS,hstyle:v,pr:'#1d4ed8',ac:'#06b6d4',bd:'#1d4ed8',font:'Inter,Arial,sans-serif',logo:v==='gradient'||v==='modern'?CREST:'',logoPos:'left',logoSize:60,sstyle:'color'},items:[sec('Section A','Multiple Choice Questions','10'),mcq('Which part of the cell holds genetic material?','Nucleus','Ribosome','Vacuole','Membrane')]})}</div><b>${n}</b><small>${HD[v]}</small></div>`).join('');
/* Scale each A4 header preview to its card so it never overflows or clips. */
function fitHdr(){$$('#hgal .th').forEach(t=>{const pv=t.firstElementChild;if(!pv)return;pv.style.transform='';const sc=t.clientWidth/pv.offsetWidth;pv.style.transform=`scale(${sc})`;pv.style.transformOrigin='0 0';t.style.height=Math.round(400*sc)+'px'})}
fitHdr();addEventListener('resize',fitHdr);document.fonts&&document.fonts.ready.then(fitHdr);
 $('#hgal').onclick=e=>{const c=e.target.closest('[data-h]');if(!c)return;const p=LS.get('apg_paper',null)||fromTpl(BUILTIN[0]);p.style={...DS,...p.style,hstyle:c.dataset.h};LS.set('apg_paper',p);location.href='generator.html'}}
if(PAGE==='home'&&!sessionStorage.getItem('apg_boot')){sessionStorage.setItem('apg_boot',1);const b=document.createElement('div');b.id='boot';b.innerHTML='<img src="assets/images/logo-mark.png" width="64" height="64" alt=""><b class="wm">Ask<em>Paper</em>Gen</b><small>Preparing templates · <span>0</span>%</small><div class="bar2"><i></i></div>';document.body.append(b);let n=0;const t=setInterval(()=>{n=Math.min(100,n+7+(Math.random()*9|0));$('span',b).textContent=n;$('i',b).style.width=n+'%';if(n>=100){clearInterval(t);setTimeout(()=>{b.classList.add('off');setTimeout(()=>{b.remove();document.dispatchEvent(new Event('apg-boot-done'))},500)},200)}},60)}else if(PAGE==='home')setTimeout(()=>document.dispatchEvent(new Event('apg-boot-done')),300);
/* ---- PWA ---- */
let dip=null;const standalone=matchMedia('(display-mode: standalone)').matches||navigator.standalone,ios=/iphone|ipad|ipod/i.test(navigator.userAgent),muted=()=>LS.get('apg_inst',0)>Date.now();
function ibar(txt){if(standalone||muted()||$('#ibar'))return;const b=document.createElement('div');b.id='ibar';b.className='glass';b.innerHTML=`<img src="assets/icons/icon-192.png" alt=""><div><b>Install AskPaperGen</b>${txt}</div>${txt.includes('Share')?'':'<button class="btn p s" data-install>Install</button>'}<button class="btn s" id="inx">Not now</button>`;document.body.append(b);requestAnimationFrame(()=>b.classList.add('on'));$('#inx').onclick=()=>{LS.set('apg_inst',Date.now()+6048e5);b.classList.remove('on');setTimeout(()=>b.remove(),600)};$$('[data-install]',b).forEach(x=>x.onclick=installApp)}
async function installApp(){if(dip){dip.prompt();const r=await dip.userChoice;dip=null;$('#ibar')?.remove();r.outcome==='accepted'&&toast('AskPaperGen installed')}else toast(ios?'Tap Share, then “Add to Home Screen”':standalone?'AskPaperGen is already installed':'Open your browser menu and choose “Install app”')}
$$('[data-install]').forEach(b=>b.onclick=installApp);
addEventListener('beforeinstallprompt',e=>{e.preventDefault();dip=e;$$('nav [data-install]').forEach(b=>b.style.display='');setTimeout(()=>ibar('Works offline — including Scan to Paper (OCR) — in its own window.'),1500)});
addEventListener('appinstalled',()=>{$('#ibar')?.remove();toast('AskPaperGen installed');setTimeout(()=>typeof prepareOcr==='function'&&prepareOcr(),1500)});
if(standalone)setTimeout(()=>typeof prepareOcr==='function'&&prepareOcr(true),4000);
if(ios&&!standalone)setTimeout(()=>ibar('Tap Share, then “Add to Home Screen”.'),2500);
addEventListener('offline',()=>toast('You are offline — your papers are safe on this device'));addEventListener('online',()=>toast('Back online'));
if('serviceWorker' in navigator&&(location.protocol==='https:'||location.hostname==='localhost'||location.hostname==='127.0.0.1'))addEventListener('load',()=>navigator.serviceWorker.register('sw.js').catch(()=>{}));
