/* App shell: navigation, footer, PWA install, landing page content */
const PWA_MODE=matchMedia('(display-mode: standalone)').matches||!!navigator.standalone;
document.body.classList.toggle('pwa-app',PWA_MODE);
const APP_HOME=(PWA_MODE||PAGE==='dashboard')?'dashboard.html':'index.html';
const NAV=[[APP_HOME,APP_HOME==='dashboard.html'?'dashboard':'home',APP_HOME==='dashboard.html'?'Dashboard':'Home'],['generator.html','generator','Paper Generator'],['templates.html','templates','Templates'],['about.html','about','About'],['contact.html','contact','Contact']];
$('#nav').innerHTML=`<nav class="glass"><a href="${APP_HOME}" class="logo"><img src="assets/images/logo-mark.png" alt="" width="34" height="34"><span class="wm">Ask<em>Paper</em>Gen</span></a><button class="btn" id="burger" aria-label="Menu">☰</button><div class="links">${NAV.map(n=>`<a class="l ${n[1]===PAGE?'on':''}" href="${n[0]}">${n[2]}</a>`).join('')}<span id="offp" class="offp" hidden>● Offline</span><button class="btn" data-install style="display:none">⬇ Install</button><a class="btn p" href="generator.html?new=1">Create Paper</a></div></nav>`;
$('#foot').innerHTML=`<div class="fgrid"><div class="fb"><a class="logo" href="${APP_HOME}"><img src="assets/images/logo-mark.png" width="34" height="34" alt=""><span class="wm">Ask<em>Paper</em>Gen</span></a><p>Create. Format. Print.<br>Professional exam papers, right in your browser. Drafts stay on your device. Paid exports use our account service.</p></div><div><div class="fh">// product</div><a href="dashboard.html">Dashboard</a><a href="generator.html">Paper Generator</a><a href="templates.html">Templates</a><a href="account.html">Account &amp; Points</a><a href="generator.html?scan=1">Text Scanner</a><button class="flink" data-install>Install app</button><button class="flink" id="chkupd">Check for updates</button></div><div><div class="fh">// company</div><a href="about.html">About</a><a href="contact.html">Contact</a><a href="privacy.html">Privacy</a><a href="https://ahsanamingorsi.com" target="_blank" rel="noopener">Developer portfolio</a></div><div><div class="fh">// connect</div><a href="https://github.com/ahsanamingorsi" target="_blank" rel="noopener">GitHub</a><a href="https://www.linkedin.com/in/ahsanamingorsi" target="_blank" rel="noopener">LinkedIn</a><a href="https://www.instagram.com/ahsanamingorsi" target="_blank" rel="noopener">Instagram</a><a href="https://wa.me/923495473628" target="_blank" rel="noopener">WhatsApp</a></div></div><div class="fbot"><span>© 2026 AskPaperGen. All rights reserved. <span id="ver"></span></span><span>Designed and developed by <a href="https://ahsanamingorsi.com" target="_blank" rel="noopener">Ahsan Amin Gorsi</a></span></div>`;
$('#burger').setAttribute('aria-expanded','false');$('#burger').onclick=()=>{const open=$('nav .links').classList.toggle('open');$('#burger').setAttribute('aria-expanded',String(open))};
function sizeNav(){document.documentElement.style.setProperty('--nav-height',PWA_MODE?'0px':Math.ceil($('nav').getBoundingClientRect().bottom)+'px')}sizeNav();if('ResizeObserver' in window)new ResizeObserver(sizeNav).observe($('nav'));addEventListener('resize',sizeNav);
if(PWA_MODE){
 const editorTabs=$('#gen .tabs');if(editorTabs)$('#gen').prepend(editorTabs);
 $('nav').classList.add('pwa-sidebar');$('nav').setAttribute('aria-label','App navigation');
 const icons={dashboard:'<rect x="3" y="3" width="7" height="7" rx="1"/><rect x="14" y="3" width="7" height="7" rx="1"/><rect x="3" y="14" width="7" height="7" rx="1"/><rect x="14" y="14" width="7" height="7" rx="1"/>',templates:'<rect x="4" y="3" width="16" height="18" rx="2"/><path d="M4 9h16M10 9v12"/>',plus:'<path d="M12 5v14M5 12h14"/>',scan:'<path d="M8 3H3v5M16 3h5v5M3 16v5h5M21 16v5h-5M7 9h10M7 13h10M7 17h6"/>',account:'<circle cx="12" cy="8" r="4"/><path d="M4 21v-2a8 8 0 0 1 16 0v2"/>'};
 const icon=key=>'<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.7" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true">'+icons[key]+'</svg>';
 const items=[['dashboard.html','dashboard','Dashboard','dashboard'],['templates.html','templates','Templates','templates'],['generator.html?new=1','','New paper','plus'],['generator.html?scan=1','','Scanner','scan'],['account.html','account','Account','account']];
 const bottom=document.createElement('nav');bottom.className='pwa-bottom';bottom.setAttribute('aria-label','App navigation');bottom.innerHTML=items.map(([url,page,label,key])=>'<a href="'+url+'" class="pwa-tab '+(key==='plus'?'pwa-create':'')+' '+(page===PAGE?'on':'')+'" '+(page===PAGE?'aria-current="page"':'')+' aria-label="'+label+'">'+icon(key)+'<span>'+label+'</span></a>').join('');document.body.append(bottom);
 const update=document.createElement('button');update.className='btn pwa-update';update.textContent='Check for updates';update.onclick=()=>$('#chkupd')?.click();$('nav .links').append(update);
 const scanner=document.createElement('a');scanner.className='l';scanner.href='generator.html?scan=1';scanner.textContent='Text Scanner';$('nav .links').insertBefore(scanner,$('#offp'));
 $$('nav.pwa-sidebar a.l.on').forEach(link=>link.setAttribute('aria-current','page'));
}
/* ---- landing ---- */
if(PAGE==='home'){
 const FE=['MCQs','Short Questions','Long Questions','Tables','Images','Urdu RTL Support','Custom Headers','Text Scanner','Print Ready','PDF Export'],FD=['Unlimited options','Quick marks','With answer lines','Editable grids','From your device','Right-to-left layout','Logo & 7 header designs','Photo to question','A4 print CSS','1 point per export'];
 const GL=['☑','✎','¶','▦','▣','ع','◧','⌖','⎙','⇩'];
$('#feats').innerHTML=FE.map((f,i)=>`<div class="glass feat"><span class="n">${String(i+1).padStart(2,'0')}</span><div class="ico">${GL[i]}</div><b>${f}</b><span>${FD[i]}</span></div>`).join('');
 $('#how').innerHTML=[['Choose','Pick one of eight templates or start from a blank paper.'],['Add','Type questions, or scan them from a photo.'],['Preview','Watch the A4 paper update live, with header designs and Urdu RTL.'],['Print','Print or save as PDF. Works offline once installed.']].map((h,i)=>`<div class="glass step"><span class="num">0${i+1}</span><h3>${h[0]}</h3><p>${h[1]}</p></div>`).join('');
 
 const HD={classic:'Centered title with a clean rule',banner:'Solid colour band, white text',gradient:'Blue-to-cyan gradient band',split:'Institution left, exam title pill right',ribbon:'Centered title with ribbon label',modern:'Left accent edge, modern look',seal:'Formal ornament between rules'};
$('#hgal').innerHTML=HS.map(([v,n])=>`<div class="glass tc" style="cursor:pointer" data-h="${v}"><div class="th">${render({meta:{...DM,inst:'Horizon Academy',exam:'Annual Examination',subject:'Science',cls:'Grade 9',marks:'50',time:'2 Hours'},style:{...DS,hstyle:v,pr:'#1d4ed8',ac:'#06b6d4',bd:'#1d4ed8',font:'Inter,Arial,sans-serif',logo:v==='gradient'||v==='modern'?CREST:'',logoPos:'left',logoSize:60,sstyle:'color'},items:[sec('Section A','Multiple Choice Questions','10'),mcq('Which part of the cell holds genetic material?','Nucleus','Ribosome','Vacuole','Membrane')]})}</div><b>${n}</b><small>${HD[v]}</small></div>`).join('');
/* Scale each A4 header preview to its card so it never overflows or clips. */
function fitHdr(){$$('#hgal .th').forEach(t=>{const pv=t.firstElementChild;if(!pv)return;pv.style.transform='';const sc=t.clientWidth/pv.offsetWidth;pv.style.transform=`scale(${sc})`;pv.style.transformOrigin='0 0';t.style.height=Math.round(400*sc)+'px'})}
fitHdr();addEventListener('resize',fitHdr);document.fonts&&document.fonts.ready.then(fitHdr);
 $('#hgal').onclick=e=>{const c=e.target.closest('[data-h]');if(!c)return;const p=LS.get('apg_paper',null)||fromTpl(BUILTIN[0]);p.style={...DS,...p.style,hstyle:c.dataset.h};LS.set('apg_paper',p);location.href='generator.html'}}
if(PAGE==='home'&&!sessionStorage.getItem('apg_boot')){sessionStorage.setItem('apg_boot',1);const b=document.createElement('div');b.id='boot';b.innerHTML='<img src="assets/images/logo-mark.png" width="64" height="64" alt=""><b class="wm">Ask<em>Paper</em>Gen</b><small>Preparing templates · <span>0</span>%</small><div class="bar2"><i></i></div>';document.body.append(b);let n=0;const t=setInterval(()=>{n=Math.min(100,n+7+(Math.random()*9|0));$('span',b).textContent=n;$('i',b).style.width=n+'%';if(n>=100){clearInterval(t);setTimeout(()=>{b.classList.add('off');setTimeout(()=>{b.remove();document.dispatchEvent(new Event('apg-boot-done'))},500)},200)}},60)}else if(PAGE==='home')setTimeout(()=>document.dispatchEvent(new Event('apg-boot-done')),300);
/* ---- PWA ---- */
let dip=null;const standalone=matchMedia('(display-mode: standalone)').matches||navigator.standalone,ios=/iphone|ipad|ipod/i.test(navigator.userAgent),muted=()=>LS.get('apg_inst',0)>Date.now();
function ibar(txt){if(standalone||muted()||$('#ibar'))return;const b=document.createElement('div');b.id='ibar';b.className='glass';b.innerHTML=`<img src="assets/icons/icon-192.png" alt=""><div><b>Install AskPaperGen</b>${txt}</div>${txt.includes('Share')?'':'<button class="btn p s" data-install>Install</button>'}<button class="btn s" id="inx">Not now</button>`;document.body.append(b);requestAnimationFrame(()=>b.classList.add('on'));$('#inx').onclick=()=>{LS.set('apg_inst',Date.now()+6048e5);b.classList.remove('on');setTimeout(()=>b.remove(),600)};$$('[data-install]',b).forEach(x=>x.onclick=installApp)}
async function installApp(){if(dip){dip.prompt();const r=await dip.userChoice;dip=null;$('#ibar')?.remove();r.outcome==='accepted'&&toast('AskPaperGen installed')}else toast(ios?'Tap Share, then “Add to Home Screen”':standalone?'AskPaperGen is already installed':'Open your browser menu and choose “Install app”')}
$$('[data-install]').forEach(b=>b.onclick=installApp);
addEventListener('beforeinstallprompt',e=>{e.preventDefault();dip=e;$$('nav [data-install]').forEach(b=>b.style.display='');setTimeout(()=>ibar('Works offline — including Text Scanner (OCR) — in its own window.'),1500)});
addEventListener('appinstalled',()=>{$('#ibar')?.remove();toast('AskPaperGen installed');setTimeout(()=>typeof prepareOcr==='function'&&prepareOcr(),1500)});
if(standalone)setTimeout(()=>typeof prepareOcr==='function'&&prepareOcr(true),4000);
if(ios&&!standalone)setTimeout(()=>ibar('Tap Share, then “Add to Home Screen”.'),2500);

/* ---- offline, updates ---- */
const offp=()=>{const p=$('#offp');if(p)p.hidden=navigator.onLine};offp();
addEventListener('offline',()=>{offp();toast('You are offline — editing and Text Scanner work. Sign-in and exports need internet.')});addEventListener('online',()=>{offp();toast('Back online')});
let swReg=null,updateCheck=null;
function ubar(){if($('#ubar'))return;const b=document.createElement('div');b.id='ubar';b.className='glass';b.setAttribute('role','alert');b.innerHTML='<img src="assets/images/logo-mark.png" alt=""><div><b>Update available</b>A new version of AskPaperGen is ready. Your papers are saved on this device.</div><button class="btn p s" id="upd">Update now</button><button class="btn s" id="updx">Later</button>';document.body.append(b);requestAnimationFrame(()=>b.classList.add('on'));
 $('#updx').onclick=()=>b.remove();$('#upd').onclick=()=>{if(!swReg?.waiting){b.remove();checkUpdates();return}sessionStorage.setItem('apg_upd',1);$('#upd').disabled=true;$('#upd').textContent='Updating...';swReg.waiting.postMessage('SKIP_WAITING')}}
function watchWorker(worker){if(!worker)return;const changed=()=>{if(worker.state==='installed'&&navigator.serviceWorker.controller)ubar()};worker.addEventListener('statechange',changed);changed()}
function waitForInstall(worker){return new Promise(resolve=>{let timer;const done=()=>{if(worker.state==='installed'||worker.state==='redundant'){clearTimeout(timer);worker.removeEventListener('statechange',done);resolve(worker.state)}};worker.addEventListener('statechange',done);timer=setTimeout(()=>{worker.removeEventListener('statechange',done);resolve('pending')},60000);done()})}
async function checkUpdates(manual=true){if(!swReg){if(manual)toast('Update checks are not ready yet. Open the app online over HTTPS.');return}if(swReg.waiting){ubar();return}if(!navigator.onLine){if(manual)toast('Connect to the internet to check for updates');return}if(updateCheck)return updateCheck;
 updateCheck=(async()=>{if(manual)toast('Checking for updates...');try{await swReg.update();const worker=swReg.installing;const state=worker?await waitForInstall(worker):null;if(swReg.waiting){ubar();return}if(manual)toast(state==='pending'?'Update is still downloading. You will be notified when it is ready.':state==='redundant'?'Update download failed. Please try again.':'You have the latest version')}catch{if(manual)toast('Could not check for updates. Please try again online.')}finally{updateCheck=null}})();return updateCheck}
$('#chkupd')&&($('#chkupd').onclick=()=>checkUpdates());
if('serviceWorker' in navigator&&(location.protocol==='https:'||location.hostname==='localhost'||location.hostname==='127.0.0.1')){
 const initUpdates=async()=>{try{swReg=await navigator.serviceWorker.register('sw.js',{updateViaCache:'none'});swReg.addEventListener('updatefound',()=>watchWorker(swReg.installing));watchWorker(swReg.installing);if(swReg.waiting&&navigator.serviceWorker.controller)ubar();checkUpdates(false);navigator.serviceWorker.controller?.postMessage('GET_VERSION')}catch{}};
 if(document.readyState==='complete')initUpdates();else addEventListener('load',initUpdates,{once:true});
 const resume=()=>{if(!document.hidden)checkUpdates(false)};document.addEventListener('visibilitychange',resume);addEventListener('pageshow',resume);addEventListener('focus',resume);addEventListener('online',resume);setInterval(resume,300000);
 let rl=false;navigator.serviceWorker.addEventListener('controllerchange',()=>{if(rl)return;navigator.serviceWorker.controller?.postMessage('GET_VERSION');if(sessionStorage.getItem('apg_upd')){rl=true;location.reload()}});
 navigator.serviceWorker.addEventListener('message',e=>{if(e.data?.type==='version'){const el=$('#ver');if(el)el.textContent='Version '+e.data.version+' ('+e.data.build+')'}if(e.data?.type==='ready'&&!LS.get('apg_offline',0)){LS.set('apg_offline',1);toast('AskPaperGen is ready to work offline')}});
 if(sessionStorage.getItem('apg_upd')){sessionStorage.removeItem('apg_upd');setTimeout(()=>toast('App updated'),600)}}
