/* ---------- data ---------- */
const DS={font:'Georgia,serif',size:13,head:15,qsize:13,line:1.5,align:'left',page:'A4',orient:'portrait',margin:15,pr:'#000000',ac:'#000000',tx:'#000000',bd:'#000000',hstyle:'classic',logoShape:'circle',logoSize:64,logoPos:'top',logoBorder:'accent',hdr:'center',hborder:'bottom',hgap:8,order:'inst',qstyle:'numbered',sstyle:'simple',rtl:false,logo:''};
const DM={inst:'Your School Name',exam:'Annual Examination',subject:'Subject',cls:'Class',marks:'50',time:'2 Hours',date:'',teacher:'',code:''};
const mcq=(t,a,b,c,d,m=1)=>({id:uid(),type:'mcq',text:t,opts:[a,b,c,d],marks:m}),sh=(t,m=2)=>({id:uid(),type:'short',text:t,marks:m}),lg=(t,m=5,l=4)=>({id:uid(),type:'long',text:t,marks:m,lines:l}),sec=(t,i,m='')=>({id:uid(),type:'section',title:t,instr:i,marks:m}),ins=t=>({id:uid(),type:'instr',text:t});
const stdItems=()=>[ins('Attempt all questions. Write neatly. Use of calculators is not allowed.'),sec('Section A','Multiple Choice Questions','10'),mcq('Which planet is known as the Red Planet?','Venus','Mars','Jupiter','Saturn'),mcq('The value of 7 × 8 is:','54','56','64','49'),sec('Section B','Short Questions — answer any three','6'),sh('Define photosynthesis.'),sh('Write a note on the water cycle.'),sh('What is a noun? Give two examples.'),sec('Section C','Long Questions','10'),lg('Describe the importance of education in society.',10,5)];
const urdu=()=>[ins('تمام سوالات حل کریں۔ صاف اور خوشخط لکھیں۔'),sec('حصہ اول','کثیر الانتخابی سوالات','5'),mcq('پاکستان کا قومی پھول کون سا ہے؟','گلاب','چنبیلی','سورج مکھی','گیندا'),mcq('اردو کے کل حروفِ تہجی کتنے ہیں؟','۳۵','۳۸','۴۰','۳۰'),sec('حصہ دوم','مختصر سوالات','6'),sh('اسم کی تعریف کیجیے۔ مثال بھی دیں۔'),sh('"علم بڑی دولت ہے" — اس جملے کی وضاحت کریں۔'),sec('حصہ سوم','تفصیلی سوالات','10'),lg('اپنے پسندیدہ شاعر کے بارے میں مضمون لکھیے۔',10,5)];
const mcqs=()=>[ins('Circle the correct option. Each question carries 1 mark.'),...[['2 + 2 =','3','4','5','6'],['Capital of France?','Rome','Berlin','Paris','Madrid'],['H₂O is:','Salt','Water','Oil','Acid'],['Largest ocean?','Atlantic','Indian','Arctic','Pacific'],['Square root of 81?','7','8','9','10'],['Fastest land animal?','Lion','Cheetah','Horse','Deer'],['Binary of 5?','101','110','011','111'],['Author of “Hamlet”?','Dickens','Austen','Shakespeare','Twain']].map(a=>mcq(...a))];
const quiz=()=>[ins('Answer in the space provided.'),sh('What is 12 × 12?',1),sh('Name the three states of matter.',2),sh('Spell “necessary” correctly.',1),sh('Who wrote our national anthem?',1)];
const S=o=>({...DS,...o});
const CREST='data:image/svg+xml;utf8,'+encodeURIComponent('<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 100 100"><rect width="100" height="100" fill="#0b1f4b"/><path d="M22 34l28-10 28 10v30l-28 10-28-10z" fill="#fff"/><path d="M50 24v50M26 38l24 9 24-9" stroke="#0b1f4b" stroke-width="3" fill="none"/><circle cx="50" cy="82" r="5" fill="#06b6d4"/></svg>');
const BUILTIN=[
{id:'classic',name:'Classic School',cat:'School',desc:'Traditional black & white school paper.',style:S({hstyle:'classic',hborder:'bottom'}),meta:{...DM,inst:'SCHOOL NAME',exam:'ANNUAL EXAMINATION'},items:stdItems},
{id:'modern',name:'Modern Academic',cat:'School',desc:'Clean blue accent, large header, organised sections.',style:S({logo:CREST,logoPos:'left',hstyle:'gradient',font:'Inter,Arial,sans-serif',pr:'#1d4ed8',ac:'#06b6d4',bd:'#bcd0f5',hborder:'box',sstyle:'color',qstyle:'numbered',head:16}),meta:{...DM,inst:'Horizon Academy',exam:'Term Assessment 2026'},items:stdItems},
{id:'college',name:'College Examination',cat:'College',desc:'Institution, department, semester, course code.',style:S({logo:CREST,logoPos:'top',hstyle:'seal',font:'"Times New Roman",serif',hborder:'double',sstyle:'under',pr:'#0b1f4b',ac:'#0b1f4b',bd:'#0b1f4b'}),meta:{...DM,inst:'City College of Science',exam:'Semester Examination',subject:'Course Title: Physics I',cls:'Department: Physics · Semester: 3',marks:'60',time:'3 Hours',code:'PHY-201'},items:stdItems},
{id:'mid',name:'Mid Term',cat:'Mid Term',desc:'Simple mid-term exam format.',style:S({hstyle:'ribbon',hborder:'bottom',sstyle:'box',qstyle:'lettered'}),meta:{...DM,inst:'Your School Name',exam:'MID TERM EXAMINATION',marks:'30',time:'1.5 Hours'},items:stdItems},
{id:'final',name:'Final Examination',cat:'Final',desc:'Formal final-term design with detailed header.',style:S({logo:CREST,logoPos:'right',hstyle:'banner',font:'"Times New Roman",serif',hborder:'box',sstyle:'box',qstyle:'boxed',pr:'#7f1d1d',ac:'#7f1d1d',bd:'#7f1d1d',head:16}),meta:{...DM,inst:'GRAMMAR HIGH SCHOOL',exam:'FINAL TERM EXAMINATION',marks:'100',time:'3 Hours',code:'F-2026'},items:stdItems},
{id:'mcq',name:'MCQ Test',cat:'MCQ',desc:'Compact layout for many MCQs per page.',style:S({hstyle:'split',font:'Arial,sans-serif',size:12,qsize:12,line:1.25,qstyle:'minimal',sstyle:'simple',hborder:'bottom',margin:12}),meta:{...DM,exam:'MCQ TEST',marks:'8',time:'15 Minutes'},items:mcqs},
{id:'quiz',name:'Quiz',cat:'Quiz',desc:'Minimal classroom quiz with name, roll and score.',style:S({hstyle:'modern',font:'Arial,sans-serif',hborder:'none',qstyle:'under',ac:'#06b6d4',pr:'#0b1f4b'}),meta:{...DM,exam:'CLASS QUIZ',inst:'Student Name: ____________   Roll No: ______',subject:'Date: ________',cls:'Score: ___ / 5',marks:'5',time:'10 Min',teacher:''},items:quiz},
{id:'urdu',name:'Urdu Examination',cat:'Urdu',desc:'RTL layout with Urdu typography and sample content.',style:S({hstyle:'ribbon',font:'"Noto Nastaliq Urdu","Jameel Noori Nastaleeq","Noto Naskh Arabic","Segoe UI",serif',rtl:true,line:2,size:14,hborder:'bottom',sstyle:'box',qstyle:'numbered',pr:'#064e3b',ac:'#064e3b'}),meta:{...DM,inst:'گورنمنٹ ہائی اسکول',exam:'سالانہ امتحان',subject:'اردو',cls:'جماعت: نہم',marks:'50',time:'۲ گھنٹے'},items:urdu}].map(t=>({...t,builtin:true}));
function fromTpl(t){const it=typeof t.items==='function'?t.items():clone(t.items);return{meta:{...t.meta},style:{...DS,...t.style},items:it.map(i=>({...i,id:uid()}))}}
