/* Scan to Paper: image -> crop/rotate/clean -> OCR provider -> structured questions -> the existing paper model.
   Providers are swappable (Extraction.providers). 'local' = Tesseract.js on this device (uses vendor/ocr if bundled, else CDN);
   'endpoint' = your own HTTPS service (see server/cloudflare-worker.js) — recommended for handwriting. */
class ScanErr extends Error{}
const OCR_CFG={provider:'auto',langs:'urd+eng',endpoint:'',mode:'printed',enh:false,...LS.get('apg_ocr',{})},saveCfg=()=>LS.set('apg_ocr',OCR_CFG);

/* ---- image tools ---- */
const mkCv=(w,h)=>{const c=document.createElement('canvas');c.width=w;c.height=h;return c};
function fromImg(img){const k=Math.min(1,2000/Math.max(img.naturalWidth,img.naturalHeight)),c=mkCv(Math.round(img.naturalWidth*k),Math.round(img.naturalHeight*k));c.getContext('2d').drawImage(img,0,0,c.width,c.height);return c}
function rotate(cv,dir){const c=mkCv(cv.height,cv.width),x=c.getContext('2d');x.translate(c.width/2,c.height/2);x.rotate(dir*Math.PI/2);x.drawImage(cv,-cv.width/2,-cv.height/2);return c}
function cropCv(cv,r){const c=mkCv(r.w,r.h);c.getContext('2d').drawImage(cv,r.x,r.y,r.w,r.h,0,0,r.w,r.h);return c}
function sharp(cv){const w=300,h=Math.max(10,Math.round(cv.height*w/cv.width)),c=mkCv(w,h),x=c.getContext('2d');x.drawImage(cv,0,0,w,h);const d=x.getImageData(0,0,w,h).data,g=new Float32Array(w*h);for(let i=0;i<w*h;i++)g[i]=.3*d[i*4]+.59*d[i*4+1]+.11*d[i*4+2];let s=0,s2=0,n=0;for(let y=1;y<h-1;y++)for(let X=1;X<w-1;X++){const k=y*w+X,l=4*g[k]-g[k-1]-g[k+1]-g[k-w]-g[k+w];s+=l;s2+=l*l;n++}return s2/n-(s/n)**2}
/* "Clean scan": adaptive threshold (local mean via integral image) — removes shadows and uneven light, helps printed and handwritten text. */
function binarize(c,hand){const w=c.width,h=c.height,x=c.getContext('2d'),im=x.getImageData(0,0,w,h),d=im.data,g=new Uint8ClampedArray(w*h),W1=w+1,I=new Float64Array(W1*(h+1));for(let i=0;i<w*h;i++)g[i]=.299*d[i*4]+.587*d[i*4+1]+.114*d[i*4+2];
 for(let y=0;y<h;y++){let s=0;for(let X=0;X<w;X++){s+=g[y*w+X];I[(y+1)*W1+X+1]=I[y*W1+X+1]+s}}
 const r=Math.max(8,Math.round(Math.min(w,h)/(hand?18:24))),C=hand?12:8;
 for(let y=0;y<h;y++){const y0=Math.max(0,y-r),y1=Math.min(h-1,y+r);for(let X=0;X<w;X++){const x0=Math.max(0,X-r),x1=Math.min(w-1,X+r),n=(x1-x0+1)*(y1-y0+1),s=I[(y1+1)*W1+x1+1]-I[y0*W1+x1+1]-I[(y1+1)*W1+x0]+I[y0*W1+x0],v=g[y*w+X]<s/n-C?0:255,k=(y*w+X)*4;d[k]=d[k+1]=d[k+2]=v;d[k+3]=255}}
 x.putImageData(im,0,0);return c}
/* Handwriting on notebook paper: keep only pen ink (blue/dark), drop red margin lines, then erase long thin underlines. Falls back to adaptive threshold. */
function inkClean(c){const w=c.width,h=c.height,x=c.getContext('2d'),im=x.getImageData(0,0,w,h),d=im.data,m=new Uint8Array(w*h);let n=0;
 for(let i=0;i<w*h;i++){const r=d[i*4],g=d[i*4+1],b=d[i*4+2],mx=Math.max(r,g,b),mn=Math.min(r,g,b),v=mx/255,s=mx?(mx-mn)/mx:0;if(((b>r+18&&b>=g-6&&s>.27&&v<.8)||v<.33)&&!(r>g+40&&r>b+40)){m[i]=1;n++}}
 if(n<w*h*.004||n>w*h*.35)return binarize(c,true);
 for(let y=4;y<h-4;y++){let s=-1;for(let X=0;X<=w;X++){const on=X<w&&m[y*w+X];if(on&&s<0)s=X;if(!on&&s>=0){if(X-s>=90){let up=0,dn=0;for(let k=s;k<X;k++){up+=m[(y-4)*w+k];dn+=m[(y+4)*w+k]}if(up<(X-s)*.2||dn<(X-s)*.2)for(let k=s;k<X;k++)for(let dy=-1;dy<=1;dy++)m[(y+dy)*w+k]=0}s=-1}}}
 for(let i=0;i<w*h;i++){const v=m[i]?0:255,k=i*4;d[k]=d[k+1]=d[k+2]=v;d[k+3]=255}x.putImageData(im,0,0);return c}
function prep(cv,hand,enh){const k=cv.width<1600?Math.min(2,1600/cv.width):1,c=mkCv(Math.round(cv.width*k),Math.round(cv.height*k));c.getContext('2d').drawImage(cv,0,0,c.width,c.height);return enh?(hand?inkClean(c):binarize(c,false)):c}
/* ---- OCR engines ---- */
let VND=null,vP=null;const vendorP=()=>vP||(vP=fetch('vendor/ocr/files.json',{cache:'no-store'}).then(r=>r.ok).catch(()=>false).then(v=>VND=v));vendorP();
const CDN='https://cdn.jsdelivr.net/npm/tesseract.js@5/dist/tesseract.min.js';let tessP=null;
const loadTess=()=>tessP||(tessP=vendorP().then(v=>new Promise((res,rej)=>{if(window.Tesseract)return res();const s=document.createElement('script');s.src=v?'vendor/ocr/tesseract.min.js':CDN;s.onload=res;s.onerror=()=>{tessP=null;rej(new Error('load'))};document.head.append(s)})));
async function mkWorker(cfg,onP){await loadTess();const o={logger:m=>m.status==='recognizing text'&&onP&&onP(Math.round(m.progress*100))};if(await vendorP())Object.assign(o,{workerPath:'vendor/ocr/worker.min.js',corePath:'vendor/ocr/core',langPath:'vendor/ocr/lang',workerBlobURL:false,gzip:true});return Tesseract.createWorker(cfg.langs,1,o)}
const httpsOk=()=>/^https:\/\//.test(OCR_CFG.endpoint||''),effProv=()=>OCR_CFG.provider==='auto'?(OCR_CFG.mode==='handwriting'&&httpsOk()?'endpoint':'local'):OCR_CFG.provider;
const TYP=[['mcq','MCQ'],['short','Short Question'],['long','Long Question'],['tf','True / False'],['fill','Fill in the Blank'],['instr','Instruction'],['section','Section Heading']];
const Extraction={providers:{
 async local(cv,cfg,onP){const w=await mkWorker(cfg,onP);try{await w.setParameters({tessedit_pageseg_mode:cfg.mode==='handwriting'?'6':'3',preserve_interword_spaces:'1'});const{data}=await w.recognize(cv);return{text:data.text,confidence:data.confidence}}finally{await w.terminate()}},
 async endpoint(cv,cfg){const blob=await new Promise(r=>cv.toBlob(r,'image/jpeg',.88)),fd=new FormData();fd.append('image',blob,'question.jpg');fd.append('langs',cfg.langs);fd.append('mode',cfg.mode);const ac=new AbortController(),to=setTimeout(()=>ac.abort(),60000);let res;
  try{res=await fetch(cfg.endpoint,{method:'POST',body:fd,signal:ac.signal})}catch(e){throw new ScanErr(e.name==='AbortError'?'The extraction service took too long to respond. Please try again.':'Network error — check your internet connection and try again.')}finally{clearTimeout(to)}
  if(!res.ok)throw new ScanErr('The extraction service returned an error ('+res.status+'). Please try again later.');let j;try{j=await res.json()}catch{throw new ScanErr('The extraction service sent a response that could not be read.')}return{text:j.text||'',confidence:j.confidence,questions:j.questions}}},
 async run(cv,onP){const prov=effProv();if(prov==='endpoint'&&!httpsOk())throw new ScanErr('Enter a secure (https) extraction endpoint in Extraction settings first.');
  let r;try{r=await this.providers[prov](cv,OCR_CFG,onP)}catch(e){if(e instanceof ScanErr)throw e;throw new ScanErr(navigator.onLine?'Reading failed. Try a clearer image, or check the extraction settings.':'You are offline and the OCR engine is not available on this device yet. Connect once to download it (Extraction settings → Download OCR), or bundle it with scripts/vendor-ocr.mjs.')}finally{cv.width=cv.height=0}
  const raw=(r.text||'').trim();if(!raw&&!(r.questions||[]).length)throw new ScanErr('No text was detected in this image. Try a closer, well-lit, straight-on photo.');
  if(raw.replace(/[^\p{L}\p{N}]/gu,'').length<3&&!(r.questions||[]).length)throw new ScanErr('The text in this image could not be read. Try a sharper, closer photo.');
  const list=Array.isArray(r.items)&&r.items.length?r.items:Array.isArray(r.questions)&&r.questions.length?r.questions:null,doc=parseDoc(raw);
  let qs=list?list.map(q=>({type:TYP.some(t=>t[0]===q.type)?q.type:'short',text:String(q.text||q.title||''),sub:String(q.sub||q.instructions||''),opts:[...(q.options||[]),'','','',''].slice(0,4).map(String),marks:q.marks||'',sure:true})):doc.items;
  if(!qs.length)qs=[classify({t:raw,o:['','','','']})];qs.forEach(q=>q.on=true);return{text:raw,confidence:r.confidence,questions:qs,meta:r.meta||doc.meta}}};
/* ---- UI ---- */
const SC={meta:{},useMeta:true,openPaste:false,img:null,cv:null,qs:[],raw:'',conf:null,blur:false,mode:'pick',crop:null,cropOn:false,append:false},touch=matchMedia('(pointer:coarse)').matches||/Android|iPhone|iPad/i.test(navigator.userAgent);
const host=()=>{try{return new URL(OCR_CFG.endpoint).hostname}catch{return'the configured service'}};
const priv=()=>effProv()==='local'?'🔒 Your image is processed on this device. It is not uploaded or stored.'+(VND?' The OCR engine is bundled with the app.':' The first scan downloads the OCR engine once from a public CDN.'):`⚠ Your image will be sent to <b>${esc(host())}</b> to extract the text. AskPaperGen does not store it.`;
const fileBtn=(l,cap,pri)=>`<label class="btn ${pri?'p':''}">${l}<input type="file" accept="image/*" ${cap?'capture="environment"':''} hidden></label>`,SB=h=>$('#sb').innerHTML=h;
const offStat=()=>VND?'bundled with the app ✓ works offline':LS.get('apg_ocr_ready',0)?'downloaded ✓ works offline':'not downloaded yet';
const cfgUI=()=>`<details ${OCR_CFG.provider!=='local'&&OCR_CFG.endpoint?'open':''}><summary>Extraction settings</summary><label class="f">Provider</label><select data-cfg="provider">${[['auto','Auto — device for print, endpoint for handwriting'],['local','On this device only (private)'],['endpoint','Always use my secure endpoint']].map(o=>`<option value="${o[0]}" ${OCR_CFG.provider===o[0]?'selected':''}>${o[1]}</option>`).join('')}</select>${OCR_CFG.provider!=='local'?`<label class="f">Endpoint URL (https) — optional, best for handwriting</label><input data-cfg="endpoint" value="${esc(OCR_CFG.endpoint)}" placeholder="https://your-worker.example.workers.dev">`:''}<label class="f">Language</label><select data-cfg="langs">${[['urd+eng','English + Urdu'],['eng','English'],['urd','Urdu']].map(l=>`<option value="${l[0]}" ${OCR_CFG.langs===l[0]?'selected':''}>${l[1]}</option>`).join('')}</select><div class="priv">Offline OCR: ${offStat()}</div>${VND?'':'<button class="btn s" type="button" data-act="ocrdl">⬇ Download OCR for offline use</button>'}</details>`;
function openScan(){SC.mode='pick';$('#sm').classList.add('on');vPick()}
function closeScan(){SC.img=SC.cv=null;SC.qs=[];SC.raw='';SC.crop=null;SC.cropOn=false;SC.append=false;SC.meta={};SC.openPaste=false;$('#sm').classList.remove('on')}
function vPick(msg){SC.mode='pick';SB(`<h2>Scan to Paper</h2><p>${SC.append?'Add another image — its questions will be added to the ones already extracted.':'Take a photo of a question, upload an image, drop one here or paste it (Ctrl+V). You review everything before it is added.'}</p>${msg?`<div class="warn">${msg}</div>`:''}<div class="tools">${touch?fileBtn('📷 Take Photo',1,1):''}${fileBtn('⬆ Upload Image',0,!touch)}</div><details ${SC.openPaste?'open':''}><summary>Type or paste text instead</summary><textarea id="pasted" dir="auto" style="min-height:110px" placeholder="Paste or type questions here — numbering, options, sections and instructions are detected automatically."></textarea><button class="btn s p" data-act="paste" style="margin-top:6px">Structure this text</button></details>${cfgUI()}<div class="priv">${priv()}</div><div class="acts"><button class="btn" data-act="close">Cancel</button></div>`)}
function vPreview(msg){SC.mode='prev';const ep=effProv()==='endpoint',hand=OCR_CFG.mode==='handwriting';
 SB(`<h2>Check the image</h2>${msg?`<div class="warn">${msg}</div>`:''}${SC.blur?'<div class="warn">This image looks blurry. Retake it closer, in good light, for better results.</div>':''}<div class="chips"><span class="chip ${hand?'':'on'}" data-mode="printed">Printed</span><span class="chip ${hand?'on':''}" data-mode="handwriting">Handwritten</span></div>${hand?`<div class="warn">Handwriting: write in dark ink on plain paper and photograph it straight-on in good light. On-device OCR is unreliable for handwriting${httpsOk()?'':' — add a handwriting-capable endpoint in Extraction settings for much better results'}. Always review the text.</div>`:''}<canvas id="scv" class="sp-img" aria-label="Selected image"></canvas>
<div class="acts"><button class="btn s" data-act="rl" title="Rotate left">⟲</button><button class="btn s" data-act="rr" title="Rotate right">⟳</button>${SC.cropOn?'<button class="btn s p" data-act="apc">Apply crop</button><button class="btn s" data-act="crc">Cancel crop</button>':'<button class="btn s" data-act="crop">✂ Crop</button>'}<button class="btn s" data-act="rst">Reset</button><label class="k" style="margin:0"><input type="checkbox" id="enh" ${OCR_CFG.enh?'checked':''}> Clean scan</label></div>${SC.cropOn?'<small style="color:#8b97b5">Drag on the image to choose the area to read.</small>':''}${ep?`<label class="k"><input type="checkbox" id="cons"> I agree to send this image to ${esc(host())}</label>`:''}<div class="priv">${priv()}</div><div class="acts">${fileBtn('Retake',1)}${fileBtn('Choose Another',0)}<button class="btn p" data-act="go" ${ep?'disabled':''}>Extract Question</button><button class="btn" data-act="typed">Type text instead</button><button class="btn" data-act="close">Cancel</button></div>`);paintCv()}
function paintCv(){const d=$('#scv'),c=SC.cv;if(!d||!c)return;d.width=c.width;d.height=c.height;d.style.touchAction=SC.cropOn?'none':'';const x=d.getContext('2d'),r=SC.crop;x.drawImage(c,0,0);if(SC.cropOn&&r&&r.w>2){x.fillStyle='rgba(7,10,18,.6)';x.fillRect(0,0,c.width,c.height);x.drawImage(c,r.x,r.y,r.w,r.h,r.x,r.y,r.w,r.h);x.strokeStyle='#22d3ee';x.lineWidth=Math.max(2,c.width/250);x.strokeRect(r.x,r.y,r.w,r.h)}}
let dragP=null;const cpt=e=>{const d=e.target,b=d.getBoundingClientRect();return{x:Math.max(0,Math.min(d.width,(e.clientX-b.left)*d.width/b.width)),y:Math.max(0,Math.min(d.height,(e.clientY-b.top)*d.height/b.height))}};
document.addEventListener('pointerdown',e=>{if(e.target.id!=='scv'||!SC.cropOn)return;dragP=cpt(e);e.target.setPointerCapture(e.pointerId)});
document.addEventListener('pointermove',e=>{if(!dragP||e.target.id!=='scv')return;const p=cpt(e);SC.crop={x:Math.min(dragP.x,p.x),y:Math.min(dragP.y,p.y),w:Math.abs(p.x-dragP.x),h:Math.abs(p.y-dragP.y)};paintCv()});
document.addEventListener('pointerup',()=>{dragP=null});
function vLoad(){SB('<div class="spin"></div><h2 style="text-align:center">Reading question…</h2><p id="prog" style="text-align:center">Preparing</p>')}
const MK={subject:'Subject',cls:'Class',time:'Time',marks:'Marks',teacher:'Teacher'};
const metaCard=()=>{const e=Object.entries(SC.meta||{}).filter(([k,v])=>v&&MK[k]);return e.length?`<div class="item"><label class="k" style="margin:0"><input type="checkbox" id="usemeta" ${SC.useMeta?'checked':''}> Fill paper details found on the page</label><div style="color:#8b97b5;font-size:13px;margin-top:4px">${e.map(([k,v])=>MK[k]+': <b style="color:#e6ebf7">'+esc(v)+'</b>').join(' · ')}</div></div>`:''};
function qCard(q,i){const txt=q.type==='instr'||q.type==='section';return`<div class="item"><div class="ih"><label class="k" style="margin:0"><input type="checkbox" data-sel="${i}" ${q.on?'checked':''}> ${txt?TYP.find(t=>t[0]===q.type)[1]:'Question '+SC.qs.slice(0,i+1).filter(x=>x.type!=='instr'&&x.type!=='section').length}</label><span class="sp"><select data-ty="${i}" style="width:auto">${TYP.map(([v,n])=>`<option value="${v}" ${v===q.type?'selected':''}>${n}</option>`).join('')}</select></span></div>${q.sure?'':'<div class="warn">Type not certain — please check it.</div>'}<textarea dir="auto" data-i="${i}" data-f="t" style="min-height:64px">${esc(q.text)}</textarea>${q.type==='mcq'?q.opts.map((o,k)=>`<input dir="auto" data-i="${i}" data-f="${k}" value="${esc(o)}" placeholder="Option ${'ABCD'[k]}" style="margin-top:4px">`).join(''):''}${q.type==='section'?`<input dir="auto" data-i="${i}" data-f="s" value="${esc(q.sub||'')}" placeholder="Section instructions (optional)" style="margin-top:4px">`:''}${q.type==='instr'?'':`<label class="f">Marks (optional)</label><input type="number" data-i="${i}" data-f="m" value="${esc(q.marks)}">`}</div>`}
function vReview(){SC.mode='rev';SB(`<h2>Review extracted ${SC.qs.length>1?'questions':'question'}</h2><p>Nothing is added until you click the button below. Fix any mistakes first.</p>${SC.conf!=null&&SC.conf<65?`<div class="warn">Low confidence (${Math.round(SC.conf)}%). Handwriting, maths and Urdu need careful checking.</div>`:''}${metaCard()}${SC.qs.map(qCard).join('')}<details><summary>Edit raw text</summary><textarea dir="auto" id="raw" style="min-height:90px">${esc(SC.raw)}</textarea><div class="acts"><button class="btn s" data-act="resplit">Re-split questions</button><button class="btn s" data-act="copy">Copy text</button></div></details><div class="acts"><button class="btn p" data-act="add"></button><button class="btn" data-act="more">＋ Scan another image</button><button class="btn" data-act="again">Scan Again</button><button class="btn" data-act="close">Cancel</button></div>`);updAdd()}
function updAdd(){const n=SC.qs.filter(q=>q.on).length,b=$('[data-act=add]');if(b){b.textContent='Add Selected to Paper ('+n+')';b.disabled=!n}}
function pickFile(f){if(!/^image\//.test(f.type))return vPick('That file type is not supported. Please choose a JPG, PNG or WebP image.');if(f.size>15e6)return vPick('That image is too large (over 15 MB). Please use a smaller photo.');
 const u=URL.createObjectURL(f),im=new Image();im.onload=()=>{SC.img=im;SC.cv=fromImg(im);SC.crop=null;SC.cropOn=false;URL.revokeObjectURL(u);try{SC.blur=sharp(SC.cv)<35}catch{SC.blur=false}vPreview()};im.onerror=()=>{URL.revokeObjectURL(u);vPick('This image could not be opened. Use a JPG or PNG (iPhone HEIC photos may need “Most Compatible” format).')};im.src=u}
async function goExtract(){vLoad();try{const cv=prep(SC.cv,OCR_CFG.mode==='handwriting',OCR_CFG.enh),r=await Extraction.run(cv,p=>{const e=$('#prog');if(e)e.textContent=p+'%'});SC.raw=(SC.append&&SC.raw?SC.raw+'\n\n':'')+r.text;SC.meta={...(SC.append?SC.meta||{}:{}),...(r.meta||{})};SC.useMeta=true;SC.conf=r.confidence;SC.qs=SC.append?[...SC.qs,...r.questions]:r.questions;SC.append=false;vReview()}catch(e){vPreview(e instanceof ScanErr?e.message:'Something went wrong while reading the image. Please try again.')}}
function addScanned(){const sel=SC.qs.filter(q=>q.on&&(q.text.trim()||q.opts.some(o=>o.trim())));if(!sel.length)return toast('Nothing to add — the selected questions are empty');
 const gp=PAGE==='generator',pp=gp?paper:(LS.get('apg_paper',null)||fromTpl(BUILTIN[0]));pp.style={...DS,...pp.style};
 sel.forEach(q=>{const m=+toEn(String(q.marks||''))||0;pp.items.push(q.type==='instr'?ins(q.text):q.type==='section'?sec(q.text,q.sub||'',q.marks||''):q.type==='mcq'?mcq(q.text,...[...q.opts,'','','',''].slice(0,4),m||1):q.type==='long'?lg(q.text,m||5,4):sh(q.text,m||(q.type==='short'?2:1)))});
 if(SC.useMeta&&SC.meta)for(const k of['subject','cls','time','marks','teacher'])if(SC.meta[k])pp.meta[k]=SC.meta[k];
 const msg=sel.length+' item'+(sel.length>1?'s':'')+' added to the paper',ar=sel.some(q=>/[\u0600-\u06FF]/.test(q.text));
 if(!gp){LS.set('apg_paper',pp);sessionStorage.setItem('apg_msg',msg);location.href='generator.html';return}
 drawList();drawSettings();refresh();closeScan();toast(msg);if(ar&&!paper.style.rtl)setTimeout(()=>toast('Urdu text added — turn on “Urdu RTL” to right-align the paper'),600);setTimeout(()=>$('#list').lastElementChild?.scrollIntoView({behavior:'smooth'}),100)}
$$('[data-scan]').forEach(b=>b.onclick=openScan);
$('#sb').onchange=e=>{const t=e.target;if(t.type==='file'&&t.files[0]){pickFile(t.files[0]);t.value='';return}
 if(t.dataset.cfg){OCR_CFG[t.dataset.cfg]=t.value;saveCfg();SC.mode==='prev'?vPreview():SC.mode==='pick'&&vPick()}
 if(t.id==='cons')$('[data-act=go]').disabled=!t.checked;if(t.id==='usemeta')SC.useMeta=t.checked;if(t.id==='enh'){OCR_CFG.enh=t.checked;saveCfg()}if(t.dataset.ty!=null){SC.qs[t.dataset.ty].type=t.value;vReview()}if(t.dataset.sel!=null){SC.qs[t.dataset.sel].on=t.checked;updAdd()}};
$('#sb').oninput=e=>{const t=e.target,i=t.dataset.i;if(i==null)return;const q=SC.qs[i],f=t.dataset.f;f==='t'?q.text=t.value:f==='s'?q.sub=t.value:f==='m'?q.marks=t.value:q.opts[+f]=t.value};
$('#sb').onclick=e=>{const m=e.target.dataset.mode;if(m){OCR_CFG.mode=m;OCR_CFG.enh=m==='handwriting';saveCfg();return vPreview()}
 const a=e.target.closest('[data-act]')?.dataset.act;if(!a)return;
 if(a==='close')closeScan();if(a==='again'){SC.qs=[];SC.append=false;vPick()}if(a==='more'){SC.append=true;vPick()}if(a==='go')goExtract();if(a==='add')addScanned();if(a==='ocrdl')prepareOcr();
 if(a==='rl'||a==='rr'){SC.cv=rotate(SC.cv,a==='rl'?-1:1);SC.crop=null;SC.cropOn=false;vPreview()}if(a==='crop'){SC.cropOn=true;SC.crop=null;vPreview()}if(a==='crc'){SC.cropOn=false;SC.crop=null;vPreview()}if(a==='rst'){SC.cv=fromImg(SC.img);SC.crop=null;SC.cropOn=false;vPreview()}
 if(a==='apc'){const r=SC.crop;if(r&&r.w>20&&r.h>20)SC.cv=cropCv(SC.cv,{x:Math.round(r.x),y:Math.round(r.y),w:Math.round(r.w),h:Math.round(r.h)});SC.cropOn=false;SC.crop=null;vPreview()}
 if(a==='typed'){SC.openPaste=true;vPick()}if(a==='paste'){const t=($('#pasted').value||'').trim();if(!t)return toast('Type or paste some text first');const d=parseDoc(t);SC.raw=(SC.append&&SC.raw?SC.raw+'\n\n':'')+t;SC.meta={...(SC.append?SC.meta||{}:{}),...d.meta};SC.useMeta=true;SC.conf=null;SC.qs=SC.append?[...SC.qs,...d.items]:d.items;SC.qs.forEach(q=>q.on=true);SC.append=false;if(!SC.qs.length)return toast('No questions found in that text');vReview()}
 if(a==='copy')navigator.clipboard&&navigator.clipboard.writeText($('#raw').value).then(()=>toast('Text copied'));
 if(a==='resplit'){SC.raw=$('#raw').value;const dd=parseDoc(SC.raw);SC.qs=dd.items;SC.meta={...SC.meta,...dd.meta};SC.qs.forEach(q=>q.on=true);if(!SC.qs.length)toast('No questions found in that text');else vReview()}};
document.addEventListener('paste',e=>{if(!$('#sm').classList.contains('on'))return;const f=[...(e.clipboardData?.files||[])].find(f=>f.type.startsWith('image/'));if(f){e.preventDefault();pickFile(f)}});
$('#sm').addEventListener('dragover',e=>e.preventDefault());$('#sm').addEventListener('drop',e=>{e.preventDefault();const f=[...e.dataTransfer.files].find(f=>f.type.startsWith('image/'));f?pickFile(f):toast('Drop an image file')});
/* Downloads the OCR engine + language data once (CDN route) so Scan to Paper keeps working offline. Not needed when vendor/ocr is bundled. */
async function prepareOcr(silent){await vendorP();if(VND)return silent||toast('OCR is bundled with the app and already works offline');if(silent&&LS.get('apg_ocr_ready',0))return;if(!navigator.onLine)return silent||toast('Connect to the internet once to download OCR');
 try{silent||toast('Downloading OCR for offline use…');const w=await mkWorker(OCR_CFG);await w.terminate();LS.set('apg_ocr_ready',1);toast('Scan to Paper (OCR) is ready for offline use')}catch{silent||toast('Could not download OCR. Check your connection and try again.')}}
