/* ===================== SCAN TO PAPER =====================
 Image -> Extraction.run() -> structured questions -> existing mcq()/sh()/lg() items -> paper.
 Providers are replaceable. A custom endpoint must accept POST multipart (fields: image, langs) and return
 JSON {text:"...", confidence?:0-100, questions?:[{type:'mcq|short|long|tf|fill',text,options:[],marks}]}. */
class ScanErr extends Error{}
const OCR_CFG={provider:'local',langs:'urd+eng',endpoint:'',...LS.get('apg_ocr',{})};
const toEn=s=>s.replace(/[٠-٩]/g,d=>d.charCodeAt(0)-1632).replace(/[۰-۹]/g,d=>d.charCodeAt(0)-1776);
/*SCAN-PARSE*/
const QS=/^(?:(?:Q(?:uestion)?|سوال(?:\s*نمبر)?)\s*[.:#-]?\s*)?([0-9٠-٩۰-۹]{1,3})\s*[.)\-:۔،](?![0-9٠-٩۰-۹])\s*(.*)$/i,OP=/^\(?\s*([a-dA-D]|الف|ب|ج|د)\s*[).:\-]\s*(.*)$/;
const CUES=[['tf',/true\s*(?:or|\/|-)\s*false|\bT\s*\/\s*F\b|صحیح\s*یا\s*غلط|درست\s*یا\s*غلط/i],['fill',/_{2,}|\.{4,}|…|خالی\s*جگہ|fill in the blank/i]];
function classify(b){let t=b.t.trim(),m='';const mm=t.match(/[\[(]\s*([0-9٠-٩۰-۹]{1,2})\s*(?:marks?|نمبر(?:ات)?)?\s*[\])]\s*$/i);if(mm){m=toEn(mm[1]);t=t.slice(0,mm.index).trim()}
 const o=b.o.map(x=>x.trim());let ty='short',sure=false;
 if(o.length>=2){ty='mcq';sure=true}else{const c=CUES.find(c=>c[1].test(t));if(c){ty=c[0];sure=true}else if(t.length>180||/\b(explain|describe|discuss|elaborate|differentiate|compare|essay)\b|تفصیل|مضمون|وضاحت/i.test(t))ty='long'}
 return{type:ty,text:t,opts:[...o,'','','',''].slice(0,4),marks:m,sure}}
function parseText(raw){const L=[];for(let l of raw.replace(/\r/g,'').split('\n')){l=l.replace(/[ \t\u00a0]+/g,' ').trim();if(!l)continue;
 if((l.match(/\(\s*[a-dA-D]\s*\)/g)||[]).length>=2)l.split(/(?=\(\s*[a-dA-D]\s*\))/).forEach(x=>x.trim()&&L.push(x.trim()));else L.push(l)}
 const B=[];let c=null;for(const l of L){const q=l.match(QS),o=l.match(OP);
 if(q){c={t:q[2],o:[]};B.push(c)}else if(o&&c)c.o.push(o[2]);else if(!c){c={t:l,o:[]};B.push(c)}else if(c.o.length)c.o[c.o.length-1]+=' '+l;else c.t+=(c.t?' ':'')+l}
 return B.filter(b=>b.t||b.o.length).map(classify)}
/*END-PARSE*/
function toCanvas(img){const k=Math.min(1,2000/Math.max(img.naturalWidth,img.naturalHeight)),c=document.createElement('canvas');c.width=Math.round(img.naturalWidth*k);c.height=Math.round(img.naturalHeight*k);const x=c.getContext('2d');x.filter='grayscale(1) contrast(1.25)';x.drawImage(img,0,0,c.width,c.height);return c}
function sharp(img){const w=300,h=Math.max(10,Math.round(img.naturalHeight*w/img.naturalWidth)),c=document.createElement('canvas');c.width=w;c.height=h;const x=c.getContext('2d');x.drawImage(img,0,0,w,h);const d=x.getImageData(0,0,w,h).data,g=new Float32Array(w*h);for(let i=0;i<w*h;i++)g[i]=.3*d[i*4]+.59*d[i*4+1]+.11*d[i*4+2];let s=0,s2=0,n=0;for(let y=1;y<h-1;y++)for(let X=1;X<w-1;X++){const k=y*w+X,l=4*g[k]-g[k-1]-g[k+1]-g[k-w]-g[k+w];s+=l;s2+=l*l;n++}return s2/n-(s/n)**2}
let tessP=null;const loadTess=()=>tessP||(tessP=new Promise((res,rej)=>{if(window.Tesseract)return res();const s=document.createElement('script');s.src='https://cdn.jsdelivr.net/npm/tesseract.js@5/dist/tesseract.min.js';s.onload=res;s.onerror=()=>{tessP=null;rej(new Error('load'))};document.head.append(s)}));
const Extraction={providers:{
 async local(cv,cfg,onP){await loadTess();const w=await Tesseract.createWorker(cfg.langs,1,{logger:m=>m.status==='recognizing text'&&onP&&onP(Math.round(m.progress*100))});try{const{data}=await w.recognize(cv);return{text:data.text,confidence:data.confidence}}finally{await w.terminate()}},
 async endpoint(cv,cfg){const blob=await new Promise(r=>cv.toBlob(r,'image/jpeg',.85)),fd=new FormData();fd.append('image',blob,'question.jpg');fd.append('langs',cfg.langs);const ac=new AbortController(),to=setTimeout(()=>ac.abort(),60000);let res;
  try{res=await fetch(cfg.endpoint,{method:'POST',body:fd,signal:ac.signal})}catch(e){throw new ScanErr(e.name==='AbortError'?'The extraction service took too long to respond. Please try again.':'Network error — check your internet connection and try again.')}finally{clearTimeout(to)}
  if(!res.ok)throw new ScanErr('The extraction service returned an error ('+res.status+'). Please try again later.');let j;try{j=await res.json()}catch{throw new ScanErr('The extraction service sent a response that could not be read.')}return{text:j.text||'',confidence:j.confidence,questions:j.questions}}},
 async run(img,onP){const cfg=OCR_CFG;if(cfg.provider==='endpoint'&&!/^https:\/\//.test(cfg.endpoint||''))throw new ScanErr('Enter a secure (https) extraction endpoint in Extraction settings first.');
  const cv=toCanvas(img);let r;try{r=await this.providers[cfg.provider](cv,cfg,onP)}catch(e){if(e instanceof ScanErr)throw e;throw new ScanErr('Reading failed. If this is your first scan, check your internet connection (the OCR engine downloads once) and try again.')}finally{cv.width=cv.height=0}
  const raw=(r.text||'').trim();if(!raw&&!(r.questions||[]).length)throw new ScanErr('No text was detected in this image. Try a closer, well-lit, straight-on photo.');
  if(raw.replace(/[^\p{L}\p{N}]/gu,'').length<3&&!(r.questions||[]).length)throw new ScanErr('The text in this image could not be read. Try a sharper, closer photo.');
  let qs=Array.isArray(r.questions)&&r.questions.length?r.questions.map(q=>({type:TYP.some(t=>t[0]===q.type)?q.type:'short',text:String(q.text||''),opts:[...(q.options||[]),'','','',''].slice(0,4).map(String),marks:q.marks||'',sure:true})):parseText(raw);
  if(!qs.length)qs=[classify({t:raw,o:[]})];qs.forEach(q=>q.on=true);return{text:raw,confidence:r.confidence,questions:qs}}};
/* ---- UI ---- */
const TYP=[['mcq','MCQ'],['short','Short Question'],['long','Long Question'],['tf','True / False'],['fill','Fill in the Blank']];
const SC={img:null,url:null,qs:[],raw:'',conf:null,blur:false,mode:'pick'},touch=matchMedia('(pointer:coarse)').matches||/Android|iPhone|iPad/i.test(navigator.userAgent);
const host=()=>{try{return new URL(OCR_CFG.endpoint).hostname}catch{return'the configured service'}};
const priv=()=>OCR_CFG.provider==='local'?'🔒 Your image is processed on this device. It is not uploaded or stored. The first scan downloads the OCR engine and language data once from a public CDN.':`⚠ Your image will be sent to <b>${esc(host())}</b> to extract the text. AskPaperGen does not store it.`;
const fileBtn=(l,cap,pri)=>`<label class="btn ${pri?'p':''}">${l}<input type="file" accept="image/*" ${cap?'capture="environment"':''} hidden></label>`;
const SB=h=>$('#sb').innerHTML=h;
function openScan(){SC.mode='pick';$('#sm').classList.add('on');vPick()}
function closeScan(){if(SC.url)URL.revokeObjectURL(SC.url);SC.img=SC.url=null;SC.qs=[];SC.raw='';$('#sm').classList.remove('on')}
const cfgUI=()=>`<details ${OCR_CFG.provider==='endpoint'?'open':''}><summary>Extraction settings</summary><label class="f">Provider</label><select data-cfg="provider"><option value="local" ${OCR_CFG.provider==='local'?'selected':''}>On this device (private)</option><option value="endpoint" ${OCR_CFG.provider==='endpoint'?'selected':''}>Custom secure endpoint</option></select>${OCR_CFG.provider==='endpoint'?`<label class="f">Endpoint URL (https)</label><input data-cfg="endpoint" value="${esc(OCR_CFG.endpoint)}" placeholder="https://your-server.example/extract">`:''}<label class="f">Language</label><select data-cfg="langs">${[['urd+eng','English + Urdu'],['eng','English'],['urd','Urdu']].map(l=>`<option value="${l[0]}" ${OCR_CFG.langs===l[0]?'selected':''}>${l[1]}</option>`).join('')}</select><button class="btn s" type="button" data-act="ocrdl" style="margin-top:8px">⬇ Download OCR for offline use</button></details>`;
function vPick(msg){SC.mode='pick';SB(`<h2>Scan to Paper</h2><p>Take a photo of a question or upload an image. The text is extracted so you can review and edit it before anything is added.</p>${msg?`<div class="warn">${msg}</div>`:''}<div class="tools">${touch?fileBtn('📷 Take Photo',1,1):''}${fileBtn('⬆ Upload Image',0,!touch)}</div>${cfgUI()}<div class="priv">${priv()}</div><div class="acts"><button class="btn" data-act="close">Cancel</button></div>`)}
function vPreview(msg){SC.mode='prev';const ext=OCR_CFG.provider==='endpoint';SB(`<h2>Check the image</h2>${msg?`<div class="warn">${msg}</div>`:''}${SC.blur?'<div class="warn">This image looks blurry. Retake it closer, in good light, for better results.</div>':''}<img class="sp-img" src="${SC.url}" alt="Selected question image">${ext?`<label class="k"><input type="checkbox" id="cons"> I agree to send this image to ${esc(host())}</label>`:''}<div class="priv">${priv()}</div><div class="acts">${fileBtn('Retake',1)}${fileBtn('Choose Another',0)}<button class="btn p" data-act="go" ${ext?'disabled':''}>Extract Question</button><button class="btn" data-act="close">Cancel</button></div>`)}
function vLoad(){SB('<div class="spin"></div><h2 style="text-align:center">Reading question…</h2><p id="prog" style="text-align:center">Preparing</p>')}
function qCard(q,i){return`<div class="item"><div class="ih"><label class="k" style="margin:0"><input type="checkbox" data-sel="${i}" ${q.on?'checked':''}> Question ${i+1}</label><span class="sp"><select data-ty="${i}" style="width:auto">${TYP.map(([v,n])=>`<option value="${v}" ${v===q.type?'selected':''}>${n}</option>`).join('')}</select></span></div>${q.sure?'':'<div class="warn">Type not certain — please check it.</div>'}<textarea dir="auto" data-i="${i}" data-f="t" style="min-height:64px">${esc(q.text)}</textarea>${q.type==='mcq'?q.opts.map((o,k)=>`<input dir="auto" data-i="${i}" data-f="${k}" value="${esc(o)}" placeholder="Option ${'ABCD'[k]}" style="margin-top:4px">`).join(''):''}<label class="f">Marks (optional)</label><input type="number" data-i="${i}" data-f="m" value="${esc(q.marks)}"></div>`}
function vReview(){SC.mode='rev';SB(`<h2>Review extracted ${SC.qs.length>1?'questions':'question'}</h2><p>Nothing is added until you click the button below. Fix any mistakes first.</p>${SC.conf!=null&&SC.conf<65?`<div class="warn">Low confidence (${Math.round(SC.conf)}%). Handwriting, maths and Urdu need careful checking.</div>`:''}${SC.qs.map(qCard).join('')}<details><summary>Edit raw text</summary><textarea dir="auto" id="raw" style="min-height:90px">${esc(SC.raw)}</textarea><button class="btn s" data-act="resplit" style="margin-top:6px">Re-split questions</button></details><div class="acts"><button class="btn p" data-act="add"></button><button class="btn" data-act="again">Scan Again</button><button class="btn" data-act="close">Cancel</button></div>`);updAdd()}
function updAdd(){const n=SC.qs.filter(q=>q.on).length,b=$('[data-act=add]');if(b){b.textContent='Add Selected to Paper ('+n+')';b.disabled=!n}}
function pickFile(f){if(!/^image\//.test(f.type)){return vPick('That file type is not supported. Please choose a JPG, PNG or WebP image.')}if(f.size>15e6)return vPick('That image is too large (over 15 MB). Please use a smaller photo.');
 const u=URL.createObjectURL(f),im=new Image();im.onload=()=>{if(SC.url)URL.revokeObjectURL(SC.url);SC.img=im;SC.url=u;try{SC.blur=sharp(im)<35}catch{SC.blur=false}vPreview()};im.onerror=()=>{URL.revokeObjectURL(u);vPick('This image could not be opened. Use a JPG or PNG (iPhone HEIC photos may need “Most Compatible” format).')};im.src=u}
async function goExtract(){vLoad();try{const r=await Extraction.run(SC.img,p=>{const e=$('#prog');if(e)e.textContent=p+'%'});SC.raw=r.text;SC.conf=r.confidence;SC.qs=r.questions;vReview()}catch(e){vPreview(e instanceof ScanErr?e.message:'Something went wrong while reading the image. Please try again.')}}
function addScanned(){const sel=SC.qs.filter(q=>q.on&&(q.text.trim()||q.opts.some(o=>o.trim())));if(!sel.length)return toast('Nothing to add — the selected questions are empty');
 const gp=PAGE==='generator',pp=gp?paper:(LS.get('apg_paper',null)||fromTpl(BUILTIN[0]));pp.style={...DS,...pp.style};
 sel.forEach(q=>{const m=+toEn(String(q.marks||''))||0;pp.items.push(q.type==='mcq'?mcq(q.text,...[...q.opts,'','','',''].slice(0,4),m||1):q.type==='long'?lg(q.text,m||5,4):sh(q.text,m||(q.type==='short'?2:1)))});
 const msg=sel.length+' question'+(sel.length>1?'s':'')+' added to the paper',ar=sel.some(q=>/[\u0600-\u06FF]/.test(q.text));
 if(!gp){LS.set('apg_paper',pp);sessionStorage.setItem('apg_msg',msg);location.href='generator.html';return}
 drawList();refresh();closeScan();toast(msg);if(ar&&!paper.style.rtl)setTimeout(()=>toast('Urdu text added — turn on “Urdu RTL” to right-align the paper'),600);setTimeout(()=>$('#list').lastElementChild?.scrollIntoView({behavior:'smooth'}),100)}
$$('[data-scan]').forEach(b=>b.onclick=openScan);
$('#sb').onchange=e=>{const t=e.target;if(t.type==='file'&&t.files[0]){pickFile(t.files[0]);t.value='';return}
 if(t.dataset.cfg){OCR_CFG[t.dataset.cfg]=t.value;LS.set('apg_ocr',OCR_CFG);SC.mode==='prev'?vPreview():SC.mode==='pick'&&vPick()}
 if(t.id==='cons')$('[data-act=go]').disabled=!t.checked;if(t.dataset.ty!=null){SC.qs[t.dataset.ty].type=t.value;vReview()}if(t.dataset.sel!=null){SC.qs[t.dataset.sel].on=t.checked;updAdd()}};
$('#sb').oninput=e=>{const t=e.target,i=t.dataset.i;if(i==null)return;const q=SC.qs[i],f=t.dataset.f;f==='t'?q.text=t.value:f==='m'?q.marks=t.value:q.opts[+f]=t.value};
$('#sb').onclick=e=>{const a=e.target.closest('[data-act]')?.dataset.act;if(!a)return;if(a==='close')closeScan();if(a==='ocrdl')prepareOcr();if(a==='again'){SC.qs=[];vPick()}if(a==='go')goExtract();if(a==='add')addScanned();
 if(a==='resplit'){SC.raw=$('#raw').value;SC.qs=parseText(SC.raw);SC.qs.forEach(q=>q.on=true);if(!SC.qs.length)toast('No questions found in that text');else vReview()}};

/* Downloads the OCR engine + language data once so Scan to Paper keeps working offline (cached by sw.js / IndexedDB). */
async function prepareOcr(silent){if(silent&&LS.get('apg_ocr_ready',0))return;if(!navigator.onLine)return silent||toast('Connect to the internet once to download OCR');
 try{silent||toast('Downloading OCR for offline use…');await loadTess();const w=await Tesseract.createWorker(OCR_CFG.langs,1,{});await w.terminate();LS.set('apg_ocr_ready',1);toast('Scan to Paper (OCR) is ready for offline use')}catch{silent||toast('Could not download OCR. Check your connection and try again.')}}
