/* AskPaperGen service worker — whole site works offline.
   V and CORE are rewritten by scripts/release.py on every release, so any change to the site produces a new worker
   and installed users get the "Update available" prompt. A new version waits until the user taps Update. */
const OCR='https://cdn.jsdelivr.net/npm/tesseract.js@5/dist/tesseract.min.js',V='askpapergen-2c5ce6c5',CORE=["./", "about.html", "assets/icons/apple-touch-icon.png", "assets/icons/favicon-16.png", "assets/icons/favicon-32.png", "assets/icons/favicon.ico", "assets/icons/icon-192.png", "assets/icons/icon-512.png", "assets/icons/icon-maskable-512.png", "assets/images/logo-full.png", "assets/images/logo-mark.png", "assets/images/logo.png", "assets/images/og-image.png", "contact.html", "css/about.css", "css/generator.css", "css/intro.css", "css/landing.css", "css/preview.css", "css/print.css", "css/responsive.css", "css/scan.css", "css/shell.css", "css/style.css", "css/templates.css", "css/theme.css", "generator.html", "index.html", "js/app.js", "js/data.js", "js/generator.js", "js/intro.js", "js/preview.js", "js/print.js", "js/scan-parser.js", "js/scan.js", "js/storage.js", "js/template-designer.js", "js/templates.js", "manifest.webmanifest", "robots.txt", "sitemap.xml", "templates.html", "tests/fixtures/page-mcq-5-9.txt", "tests/fixtures/page-objective.txt", "tests/fixtures/page-passage.txt", "tests/parser.test.js"];
self.addEventListener('install',e=>e.waitUntil(caches.open(V).then(async c=>{await c.addAll(CORE);
 try{const l=await (await fetch('vendor/ocr/files.json',{cache:'no-store'})).json();await c.addAll(['vendor/ocr/files.json',...l.map(f=>'vendor/ocr/'+f)])}catch{}
 try{await c.put(OCR,await fetch(new Request(OCR,{mode:'no-cors'})))}catch{}})));
self.addEventListener('activate',e=>e.waitUntil((async()=>{for(const k of await caches.keys())if(k!==V)await caches.delete(k);await clients.claim();(await clients.matchAll()).forEach(c=>c.postMessage({type:'ready',v:V}))})()));
self.addEventListener('message',e=>{if(e.data==='SKIP_WAITING')self.skipWaiting()});
self.addEventListener('fetch',e=>{const r=e.request,u=new URL(r.url);if(r.method!=='GET'||!(u.origin===location.origin||/jsdelivr|projectnaptha/.test(u.host)))return;
 e.respondWith(caches.match(r,{ignoreSearch:true}).then(hit=>{const net=fetch(r).then(res=>{if(res.ok||res.type==='opaque'){const cp=res.clone();caches.open(V).then(c=>c.put(r,cp))}return res}).catch(()=>hit||(r.mode==='navigate'?caches.match('index.html'):Response.error()));return hit||net}))});
