/* Generated release identifiers; run node scripts/release.mjs before deploying. */
const OCR='https://cdn.jsdelivr.net/npm/tesseract.js@5.1.1/dist/tesseract.min.js',V='askpapergen-2cde2046425f',VERSION={"version":"2026.10.07","build":"2cde2046425f"},CORE=["./","about.html","assets/icons/apple-touch-icon.png","assets/icons/favicon-16.png","assets/icons/favicon-32.png","assets/icons/favicon.ico","assets/icons/icon-192.png","assets/icons/icon-512.png","assets/icons/icon-maskable-512.png","assets/icons/logo.svg","assets/images/logo-full.png","assets/images/logo-mark.png","assets/images/logo.png","assets/images/og-image.png","contact.html","css/about.css","css/generator.css","css/intro.css","css/landing.css","css/preview.css","css/print.css","css/responsive.css","css/scan.css","css/shell.css","css/style.css","css/templates.css","css/theme.css","generator.html","index.html","js/app.js","js/data.js","js/generator.js","js/intro.js","js/preview.js","js/print.js","js/scan-parser.js","js/scan.js","js/storage.js","js/template-designer.js","js/templates.js","manifest.webmanifest","robots.txt","sitemap.xml","templates.html","vendor/ocr/core/tesseract-core-lstm.wasm.js","vendor/ocr/core/tesseract-core-simd-lstm.wasm.js","vendor/ocr/core/tesseract-core-simd.wasm.js","vendor/ocr/core/tesseract-core.wasm.js","vendor/ocr/files.json","vendor/ocr/lang/eng.traineddata.gz","vendor/ocr/lang/urd.traineddata.gz","vendor/ocr/tesseract.min.js","vendor/ocr/worker.min.js"];
self.addEventListener('install',e=>e.waitUntil(caches.open(V).then(async c=>{
 await c.addAll(CORE.map(url=>new Request(url,{cache:'reload'})));let bundled=false;
 try{const r=await fetch('vendor/ocr/files.json',{cache:'no-store'});if(r.ok){const l=await r.json();await c.addAll(['vendor/ocr/files.json',...l.map(f=>'vendor/ocr/'+f)]);bundled=true}}catch{}
 if(!bundled){const ac=new AbortController(),timer=setTimeout(()=>ac.abort(),15000);try{await c.put(OCR,await fetch(new Request(OCR,{mode:'no-cors',signal:ac.signal})))}catch{}finally{clearTimeout(timer)}}
})));
self.addEventListener('activate',e=>e.waitUntil((async()=>{for(const k of await caches.keys())if(k.startsWith('askpapergen-')&&k!==V)await caches.delete(k);await self.clients.claim();(await self.clients.matchAll()).forEach(c=>c.postMessage({type:'ready',v:V}))})()));
self.addEventListener('message',e=>{if(e.data==='SKIP_WAITING')e.waitUntil(self.skipWaiting());if(e.data==='GET_VERSION')e.source?.postMessage({type:'version',...VERSION})});
self.addEventListener('fetch',e=>{const r=e.request,u=new URL(r.url);if(r.method!=='GET')return;
 const local=u.origin===self.location.origin&&u.href.startsWith(self.registration.scope),ocr=/^(?:cdn\.jsdelivr\.net|tessdata\.projectnaptha\.com)$/.test(u.hostname);if(!local&&!ocr)return;
 if(local&&u.pathname.endsWith('/version.json')){e.respondWith(fetch(new Request(r,{cache:'no-store'})).catch(()=>new Response(JSON.stringify(VERSION),{headers:{'Content-Type':'application/json'}})));return}
 // Keep each release's application files together; do not overwrite them with a later release.
 e.respondWith((async()=>{const c=await caches.open(V),hit=await c.match(r,{ignoreSearch:true});if(hit)return hit;try{const res=await fetch(r);if(ocr&&(res.ok||res.type==='opaque')){const cp=res.clone();e.waitUntil(c.put(r,cp))}return res}catch{return r.mode==='navigate'?(await c.match('index.html'))||Response.error():Response.error()}})())
});
