const fs=require('fs'),http=require('http'),path=require('path'),assert=require('assert');
const {chromium}=require(path.join(process.argv[2]||'.','playwright'));
const root=path.resolve(__dirname,'..');
const server=http.createServer((req,res)=>{let file=path.join(root,new URL(req.url,'http://localhost').pathname);if(file===root+path.sep)file=path.join(root,'index.html');fs.readFile(file,(e,b)=>{res.writeHead(e?404:200,{'Content-Type':file.endsWith('.js')?'application/javascript':file.endsWith('.css')?'text/css':'text/html'});res.end(e?'missing':b)})});
(async()=>{await new Promise(r=>server.listen(0,'127.0.0.1',r));let browser;try{
 browser=await chromium.launch({executablePath:'C:/Program Files/Google/Chrome/Application/chrome.exe',headless:true});const base='http://127.0.0.1:'+server.address().port;
 const context=await browser.newContext({serviceWorkers:'block'});await context.route('**/*',r=>new URL(r.request().url()).hostname==='127.0.0.1'?r.continue():r.abort());const page=await context.newPage();await page.goto(base+'/index.html');assert.equal(new URL(page.url()).pathname,'/index.html');await page.goto(base+'/index.html?source=pwa');await page.waitForURL('**/dashboard.html');
 const app=await browser.newContext({serviceWorkers:'block',viewport:{width:390,height:844}});await app.addInitScript(()=>{const original=window.matchMedia.bind(window);window.matchMedia=q=>q==='(display-mode: standalone)'?{matches:true,media:q,addEventListener(){},removeEventListener(){}}:original(q)});await app.route('**/*',r=>new URL(r.request().url()).hostname==='127.0.0.1'?r.continue():r.abort());const p=await app.newPage(),errors=[];p.on('pageerror',e=>errors.push(e.message));await p.goto(base+'/index.html');await p.waitForURL('**/dashboard.html');assert.equal(await p.locator('nav .logo').getAttribute('href'),'dashboard.html');assert.equal(await p.locator('#boot').count(),0);assert.match(await p.locator('#dashboard-current').textContent(),/No current paper/);
 await p.evaluate(()=>{localStorage.setItem('apg_paper',JSON.stringify({meta:{subject:'<script>unsafe</script>',inst:'Test School'},items:[{type:'short',text:'Question'}]}));localStorage.setItem('apg_drafts',JSON.stringify([{p:{},t:'today'}]))});await p.reload();assert.match(await p.locator('#dashboard-current').textContent(),/1 questions/);assert.equal(await p.locator('#dashboard-current script').count(),0);assert.match(await p.locator('#dashboard-drafts').textContent(),/1 saved drafts/);assert.deepEqual(errors,[]);
 for(const width of [280,320,390,768,1024,1280,1440,1920]){await p.setViewportSize({width,height:844});for(const file of ['dashboard.html','generator.html','templates.html','account.html']){await p.goto(base+'/'+file);await p.evaluate(()=>{document.querySelector('#intro')?.remove()});await p.waitForTimeout(100);assert(await p.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+2),file+' overflow at '+width+' '+JSON.stringify(await p.evaluate(()=>[...document.querySelectorAll('body *')].filter(e=>e.getBoundingClientRect().right>innerWidth+2).slice(0,10).map(e=>({tag:e.tagName,cls:e.className,r:e.getBoundingClientRect().right})))));if(width<=1100){assert(await p.locator('.pwa-bottom').isVisible());assert.equal(await p.locator('.pwa-sidebar').isVisible(),false);const box=await p.locator('.pwa-create').boundingBox();assert(Math.abs(box.x+box.width/2-width/2)<2,'centered create action');if(file==='generator.html'&&width<=900){assert(await p.locator('.tabs').isVisible());const tabs=await p.locator('.tabs').boundingBox(),bottom=await p.locator('.pwa-bottom').boundingBox();if(width<=900)assert(tabs.y+tabs.height<bottom.y,'editor tabs do not overlap app navigation')}}else{assert(await p.locator('.pwa-sidebar').isVisible());assert.equal(await p.locator('.pwa-bottom').isVisible(),false)}}}
 await p.setViewportSize({width:390,height:844});await p.goto(base+'/dashboard.html');fs.mkdirSync(path.join(root,'.tmp'),{recursive:true});await p.screenshot({path:path.join(root,'.tmp','pwa-dashboard-mobile.png'),fullPage:true});await p.setViewportSize({width:1440,height:900});await p.screenshot({path:path.join(root,'.tmp','pwa-dashboard-desktop.png'),fullPage:true});assert.deepEqual(errors,[]);
 const manifest=JSON.parse(fs.readFileSync(path.join(root,'manifest.webmanifest'),'utf8'));assert.equal(manifest.start_url,'./dashboard.html?source=pwa');assert.equal(manifest.id,'./');assert(fs.readFileSync(path.join(root,'sw.js'),'utf8').includes('"dashboard.html"'));console.log('PASS browser landing, PWA launch, sidebar and centered mobile navigation, saved paper and four app pages at eight screen sizes');
 }finally{if(browser)await browser.close();await new Promise(r=>server.close(r))}})().catch(e=>{console.error(e);process.exitCode=1});
