// node tests/responsive.browser.test.js <directory containing playwright> [--audit]
const fs=require('fs'),http=require('http'),path=require('path'),assert=require('assert');
const {chromium}=require(process.argv[2]?path.join(process.argv[2],'playwright'):'playwright');const root=path.resolve(__dirname,'..');
const types={'.html':'text/html','.js':'application/javascript','.css':'text/css','.json':'application/json','.svg':'image/svg+xml','.png':'image/png'};
const server=http.createServer((req,res)=>{let file=path.resolve(root,'.'+decodeURIComponent(new URL(req.url,'http://localhost').pathname));if(file===root)file=path.join(root,'index.html');if(!file.startsWith(root+path.sep)){res.writeHead(403);return res.end()}fs.readFile(file,(err,data)=>{res.writeHead(err?404:200,{'Content-Type':types[path.extname(file)]||'application/octet-stream'});res.end(err?'Not found':data)})});
(async()=>{await new Promise(r=>server.listen(0,'127.0.0.1',r));let browser;const failures=[];try{
 browser=await chromium.launch({executablePath:process.env.APG_CHROME||'C:/Program Files/Google/Chrome/Application/chrome.exe',headless:true});const context=await browser.newContext({serviceWorkers:'block',reducedMotion:'reduce'});await context.route('**/*',r=>new URL(r.request().url()).hostname==='127.0.0.1'?r.continue():r.abort());const page=await context.newPage();page.on('pageerror',e=>failures.push('JS: '+e.message));
 const check=async(label)=>{await page.waitForTimeout(50);const info=await page.evaluate(()=>({width:innerWidth,scroll:document.documentElement.scrollWidth,offenders:[...document.querySelectorAll('body *')].filter(e=>{const r=e.getBoundingClientRect(),s=getComputedStyle(e);return r.width>0&&s.position!=='fixed'&&r.right>innerWidth+2&&!e.closest('.pv,#designer,.modal,#intro')}).slice(0,8).map(e=>e.tagName+'.'+e.className)}));if(info.scroll>info.width+2)failures.push(label+' overflow '+JSON.stringify(info))};
 const sizes=[[280,640],[320,640],[360,740],[390,844],[560,800],[768,1024],[900,700],[1024,768],[1100,800],[1280,800],[1440,900],[1920,1080],[2560,1440],[844,390]];
 for(const [width,height] of sizes){await page.setViewportSize({width,height});for(const file of ['index.html','about.html','contact.html','templates.html','generator.html']){await page.goto('http://127.0.0.1:'+server.address().port+'/'+file,{waitUntil:'domcontentloaded'});await page.evaluate(()=>{sessionStorage.setItem('apg_boot','1');document.querySelector('#boot')?.remove();document.querySelector('#intro')?.remove()});await check(file+' '+width);if(width<=1100){await page.locator('#burger').click();await check('menu '+file+' '+width);await page.locator('#burger').click()}if(process.argv.includes('--screens')&&['index.html','generator.html'].includes(file)&&[320,768,1024].includes(width)){fs.mkdirSync(path.join(root,'.tmp'),{recursive:true});await page.screenshot({path:path.join(root,'.tmp',file+'-'+width+'.png'),fullPage:true})}
 if(file==='generator.html'){
 if(width<=900){for(const tab of ['content','settings','preview']){await page.locator('.tabs [data-t='+tab+']').click();if(tab==='content')await page.locator('[data-add=mcq]').click();if(tab==='settings')await page.locator('#meta input').first().fill('Responsive school name');await check('generator '+tab+' '+width)}}
 const geometry=await page.locator('#gp .pv').evaluate(e=>{const r=e.getBoundingClientRect(),c=e.closest('.center').getBoundingClientRect();return {width:r.width,left:r.left,right:r.right,container:c.width}});if(geometry.width<100||geometry.right>width+2)failures.push('Preview '+width+' '+JSON.stringify(geometry));
 if(width>900&&width<=1200){await page.locator('#togR').click();await page.locator('.drawer-close').click()}await page.evaluate(()=>openPrev(paper));await check('paper dialog '+width);await page.evaluate(()=>$('#pm').classList.remove('on'));await page.evaluate(()=>openScan());await check('scanner '+width);await page.evaluate(()=>{SC.raw='English text\nUrdu text';SC.qs=Array.from({length:4},()=>({type:'mcq',text:'Review scanned question text',opts:['A','B','C','D'],sure:true,on:true}));vReview()});await check('scanner review '+width);await page.evaluate(()=>closeScan());
 }
 if(file==='templates.html'){await page.evaluate(()=>openDesigner());await check('designer '+width);const b=await page.locator('#dp .pv').boundingBox();if(!b||b.width<100||b.x+b.width>width+2)failures.push('Designer preview '+width+' '+JSON.stringify(b));await page.evaluate(()=>closeDesigner())}
 }}
 console.log(failures.length?failures.join('\n'):'PASS all five pages, generator tabs, scanner and template designer at 14 screen sizes');if(!process.argv.includes('--audit'))assert.equal(failures.length,0,'Responsive layout failures');
 }finally{if(browser)await browser.close();await new Promise(r=>server.close(r))}})().catch(e=>{console.error(e);process.exitCode=1});
